name: Sync Kernel Source

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'

    - name: Clone the Android kernel source
      run: |
        git clone https://android.googlesource.com/kernel/common android_kernel_source
        cd android_kernel_source
        git checkout 3ca6a2912c7e # 指定要同步的提交ID

    - name: Copy the kernel source to the repository
      run: |
        cp -r android_kernel_source/* .
        rm -rf android_kernel_source

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Sync kernel source from android.googlesource.com" || true
        git push origin main
