name: Sync Android Kernel Source

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  sync-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Clone Android kernel source
      run: |
        git clone https://android.googlesource.com/kernel/common.git
        cd common
        git checkout 3ca6a2912c7e

    - name: Push to GitHub
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # 添加目标仓库的远程 URL，并使用 GITHUB_TOKEN 进行身份验证
        cd common
        git remote add destination https://$TOKEN@github.com/3582730951/MiLinuxKernel_2.git
        git checkout -b k60pro_2  # 创建并切换到新分支

        # 推送代码到新的分支
        git push destination k60pro_2
