name: Sync Google Kernel to GitHub

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * 1'  # 每周一自动触发

jobs:
  sync_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the GitHub repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone Google Kernel repository
        run: |
          git clone https://android.googlesource.com/kernel/common.git
          cd common
          git checkout 3ca6a2912c7e

      - name: Copy Google Kernel to GitHub repository
        run: |
          rsync -a --exclude='.git' common/ .  # 修正路径为 common/

      - name: Commit and push changes to k60pro branch on GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b k60pro  # 切换到 k60pro 分支
          git add .
          git commit -m "Sync Google Kernel source at 3ca6a2912c7e"
          git push -u origin k60pro  # 推送到 k60pro 分支
