name: Sync Android Kernel Source

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  sync-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Clone Android kernel source
      run: |
        git clone https://android.googlesource.com/kernel/common.git
        cd common
        git checkout 3ca6a2912c7e

    - name: Push to GitHub
      run: |
        # 设置 Git 用户信息
        git config --global user.name "3582730951"
        git config --global user.email "3582730951@qq.com"
        
        # 配置远程仓库的 URL（使用 GitHub Secrets 中存储的 PAT）
        cd common
        git remote set-url origin https://3582730951:${{ secrets.GH_PAT }}@github.com/3582730951/MiLinuxKernel_2.git
        
        # 创建并切换到新分支
        git checkout -b k60pro_2

        # 推送代码到新的分支
        git push origin k60pro_2
